CREATE TABLE "organization_config" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"name" varchar(255),
	"slug" varchar(255),
	"domain" varchar(255),
	"contact_email" varchar(255),
	"contact_phone" varchar(20),
	"razorpay_key_id" varchar(255),
	"razorpay_key_secret" varchar(255),
	"currency" varchar(10) DEFAULT 'INR',
	"tax_percentage" varchar(10),
	"invoice_prefix" varchar(20),
	"logo_url" text,
	"favicon_url" text,
	"banner_urls" jsonb,
	"motto" varchar(255),
	"description" text,
	"theme" jsonb,
	"hero_title" varchar(255),
	"hero_subtitle" text,
	"cta_text" varchar(255),
	"cta_url" text,
	"features" jsonb,
	"testimonials" jsonb,
	"faq" jsonb,
	"social_links" jsonb,
	"meta_title" varchar(255),
	"meta_description" text,
	"og_image" text,
	"smtp_config" jsonb,
	"support_email" varchar(255),
	"features_enabled" jsonb,
	"maintenance_mode" boolean DEFAULT false,
	"custom_css" text,
	"custom_js" text,
	"is_active" boolean DEFAULT true,
	"disabled_reason" text,
	"disabled_at" timestamp,
	"reactivated_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "organization_config_organization_id_unique" UNIQUE("organization_id"),
	CONSTRAINT "organization_config_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "organization_config" ADD CONSTRAINT "organization_config_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;